spring:
  datasource:
    url: jdbc:h2:D:/H2/test
    driver-class-name: org.h2.Driver
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true